export const contents = [
  {
    id: "pdc",
    effect: "fade-up",
    mainImage: "pdc",
    subImage1: "lettuce",
    subImage2: "plantArt",
    subImage3: "plantCont",
    pageRef: "https://plant-check.vercel.app/",
  },
  {
    id: "fcc",
    effect: "fade-up",
    mainImage: "fcc",
    subImage1: "makanan",
    subImage2: "artMakanan",
    subImage3: "contMakanan",
    pageRef: "https://food-check.vercel.app/",
  },
  {
    id: "oasis",
    effect: "fade-up",
    mainImage: "oasis",
    subImage1: "cabins",
    subImage2: "reserve",
    subImage3: "guest",
    pageRef: "https://wild-oasis-website-six.vercel.app/",
  },
  {
    id: "ecommerce",
    effect: "fade-up",
    mainImage: "e_commerce",
    subImage1: "cloth",
    subImage2: "ball",
    subImage3: "products",
    pageRef: "https://online-shopping-sooty-ten.vercel.app/",
  },
  {
    id: "ummu",
    effect: "fade-up",
    mainImage: "ummu",
    subImage1: "menu",
    subImage2: "menu2",
    subImage3: "order",
    pageRef: "https://warung-ummu-yassir.vercel.app/",
  },
  {
    id: "chat",
    effect: "fade-up",
    mainImage: "chat",
    subImage1: "profile",
    subImage2: "pricing",
    subImage3: "signup",
    pageRef: "https://chatbuddy-derik-aquarys-projects.vercel.app/",
  },
];
