export const skills = [
  {
    id: 1,
    src: "/html5_gray.png",
    alt: "html logo",
    divClass: "flex items-center justify-center absolute bottom-[-20px] right-[-25px] px-[13px] py-[17px] border-[3px] border-red-400 rounded-full bg-red-400/30",
    pClass:"text-red-400",
    className: "object-cover ",
  },
  {
    id: 2,
    src: "/css_gray.png",
    alt: "CSS logo",
    divClass: "flex items-center justify-center absolute bottom-[-20px] right-[-25px] px-[13px] py-[17px] border-[3px] border-[#619fe8] rounded-full bg-[#619fe8]/30",
    pClass:"text-[#619fe8] ",
    className: "object-cover ",
  },
  {
    id: 3,
    src: "/javascript_gray.png",
    alt: "Javascript logo",
    divClass: "flex items-center justify-center absolute bottom-[-20px] right-[-25px] px-[13px] py-[17px] border-[3px] border-[#efe76d] rounded-full bg-[#efe76d]/30",
    pClass:"text-[#efe76d]",
    className: "object-cover ",
  },
  {
    id: 4,
    src: "/react_white.png",
    alt: "react logo",
    divClass: "flex items-center justify-center absolute bottom-[-20px] right-[-25px] px-[13px] py-[17px] border-[3px] border-red-400 rounded-full bg-red-400/30",
    pClass:"text-red-400",
    className: "object-cover ",
  },
  {
    id: 5,
    src: "/nextjs.png",
    alt: "Nextjs logo",
    divClass: "flex items-center justify-center absolute bottom-[-20px] right-[-25px] px-[13px] py-[17px] border-[3px] border-red-400 rounded-full bg-red-400/30",
    pClass:"text-red-400",
    className: "object-cover rounded-full",
  },
];
